# Generated by Django 3.0.5 on 2020-09-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=18)),
                ('address', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos')),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('about_us', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
